baseURL = 'https://guide.tumbleweed.games/'
languageCode = 'en-us'
defaultContentLanguage = 'en'
theme = 'hugo-book'
enableGitInfo = true

[languages]
  [languages.en]
    title = 'Tumbleweed Guide'
    languageName = 'English'
  [languages.fr]
    title = 'Tumbleweed Guide'
    languageName = 'Français'
  [languages.ja]
    title = 'タンブルウィード入門'
    languageName = '日本語'
[params]
  BookSection = '*'
  BookTheme = 'auto'
  BookRepo = 'https://github.com/nobu1308/tumbleweed-guide'
  BookEditPath = 'edit/main'
  BookComments = false
